name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Especifique a versão do Node.js

      - name: Install Dependencies
        run: cd admin-panel && npm install

      - name: Build
        run: cd admin-panel && npm run build
        env:
          VITE_BASE_PATH: /watchmoney-admin-panel/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: admin-panel/dist